// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");

var z = Fs.readFileSync("./src/day2/input.txt", "utf8");

console.log(z);

exports.z = z;
/* z Not a pure module */
