// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Fs          = require("fs");
var $$Array     = require("bs-platform/lib/js/array.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");

var input = Fs.readFileSync("./src/day2/input.txt", "utf8");

var rowsRaw = input.split("\n");

var rows = $$Array.map((function (row) {
        return $$Array.map(Caml_format.caml_int_of_string, row.split("\t"));
      }), rowsRaw);

console.log(rows);

exports.input   = input;
exports.rowsRaw = rowsRaw;
exports.rows    = rows;
/* input Not a pure module */
