// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");

var x = +Fs.existsSync("~/code/github");

console.log(x);

exports.x = x;
/* x Not a pure module */
